### ISSUE TITLE
Add multiple common number example

### ISSUE THREAD

**Issue by BootzenKatzen** [CheckiO-Missions/checkio-mission-common-tail#2]
I think it would be helpful to have another example that had 2 or 3 common elements at the end of the list to make it clear what you're looking for.  The "example" has 2 common elements, but it's not an assert, so it doesn't work as an example, and none of the other asserts have more than 1 common number at the end.  I think, from what I can understand, that if the lists were [1, 3, 4, 6] and [2, 9, 4, 6] we would return 4, yes?  It's just a lot easier to understand what you're looking for with examples that show all the possible scenarios - no common number, one common number, multiple common numbers.

**Comment by freemanlex** [comment]
Added.
